### ISSUE TITLE
小程序端，app.wxss没加载？

### ISSUE THREAD

**Issue by wufeng87** [NervJS/taro-zhihu-sample#5]
其他页面样式都正常，但是头像和feed的样式没加载上。
![image](https://user-images.githubusercontent.com/1686808/44968287-b2c5a100-af79-11e8-802e-db846db770e3.png)

**Comment by wufeng87** [comment]
大致是feed组件的样式跑到app.wxss里了，导致组件feed样式都没被加载上

**Comment by jimczj** [comment]
忘记在页面 import scss，已修复
